#time to check if one minute passed(1200 ticks) for spawning events
time-check-delay: 1200
#максимальное время при котором событие будет запущено автоматески
max-event-execute-time-difference: 60

#время анонсов ивента.
#по сколько используемый промежуток обновления ивентов нельзя предугадать
#для анонсов используется промежуток по времени. Если при обновлении таймера ивентов
# время аноса попадает в промежуток - ивент будет анонсирован
announcements:
  time: 180
  from-time: 170
  to-time: 230

can-console-command: false
time-to-nearest-events: 180 #seconds

event-possible-types:
  - mist
  - vulcan
  - other

events:
  1:
    name: "Мистик"
    type: "mist"
    description: "Мистический сундук содержащий отличный лут"
    active-time: 90 #seconds
    run-time: "" #format 'hh:mm:ss' (18:30:00)
    activation-command: "say event has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

  2:
    name: "Событие 2"
    type: "other"
    description: "Описание события 2"
    active-time: 90 #seconds
    run-time: "" #format 'hh:mm:ss' (18:30:00)
    activation-command: "say event has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

  3:
    name: "Событие 3"
    type: "other"
    description: "Описание события 3"
    active-time: 90 #seconds
    run-time: "" #format 'hh:mm:ss' (18:30:00)
    activation-command: "say event has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

