#врмя итараций для проверки систояния событий, тики
time-check-delay: 20


#максимальное время при котором событие будет запущено автоматески
#изза того, что проверка событий может быть каждые 2 или каждые 60 секунд
#попасть в точное время может быть сложно.
#этот парамерт используется каждую итерацию time-check-delay
#при проверке на анонсирование событий и их исполнение
max-event-execute-time-difference: 20

announcements:
  #время до начале ивента за которое его нужно нанонсировать
  time: 60     #seconds
  #изза того, что проверка событий может быть каждые 2 или каждые 60 секунд
  #для анонсов используется промежуток по времени. Если при итерации таймера ивентов (time-check-delay)
  #время аноса попадает в промежуток - ивент будет анонсирован
  #чем больше (time-check-delay) тем больше нужно ставить время промежутков
  from-time: 15 #seconds
  to-time: 30   #seconds

can-console-command: false

#время, используемое в команде для проверки ближайших ивентов от времени иполнения команды + time-to-nearest-events
time-to-nearest-events: 60 #seconds

#типы событий
event-possible-types:
  - mist
  - vulcan
  - other

events:
  1:
    name: "Мистик"
    type: "mist"
    description: "Мистический сундук содержащий отличный лут"
    active-time: 90 #seconds
    run-time: "14:36:00" #format 'hh:mm:ss' (18:30:00)
    activation-command: "say event 1 has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

  2:
    name: "Событие 2"
    type: "mist"
    description: "Описание события 2"
    active-time: 90 #seconds
    run-time: "14:37:00"#format 'hh:mm:ss' (18:30:00)
    activation-command: "say event 2 has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

  3:
    name: "Событие 3"
    type: "mist"
    description: "Описание события 3"
    active-time: 90 #seconds
    run-time: "14:38:00" #format 'hh:mm:ss' (18:30:00)
    activation-command: "say event 3 has been activated"
    location:
      coords:
        x: 0
        y: 0
        z: 0
      world-name: ""

