name: MelvuzeEventManager
version: '${version}'
main: me.melvuze.eventmanager.EventManager
api-version: '1.17'
author: Leopold95

commands:
  event:
    usage: "Использование: /event <args>"
    description: Дает информацию про ивенты
    permission: melvuzeevent


permissions:
  melvuzeevent:
    default: op
    description: Доступ к /event

#  melvuzeevent.list:
#    default: op
#    description: Доступ к /event open
